ShopMagazin/Controllers/CategoriiController.cs
using JWT.Algorithms;
using JWT.Builder;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Driver;
using ShopMagazin.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ShopMagazin.Controllers
{
    public class CategoriiController : Controller
    {
        private readonly TovariService db;
        private readonly UsersService dbs;
        public CategoriiController(TovariService context, UsersService contexts)
        {
            db = context;
            dbs = contexts;
        }

        public async Task<ActionResult> GetImage(string id)
        {
            var image = await db.GetImage(id);
            if (image == null)
            {
                return NotFound();
            }
            return File(image, "image/png");
        }

        public async Task<IActionResult> Podcategorii(string id, int page = 1)
        {
            PodCatG g = new PodCatG();
            g.categMain = await db.GetCategoriesPoID(id);
            g.PodCategsList = await db.GetPodCategoriesPoMainCat(g.categMain.Id);
            g.TovariList = await db.GetTovariWithFilterAndCategori(null, g.categMain.NameCategori, null);
            g.KolTovarov = g.TovariList.Count().ToString();

            var count = g.TovariList.Count();
            int pageSize = 10;
            var item = g.TovariList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            g.PageViewModel = new PageViewModel(count, page, pageSize);
            g.TovariList = item;

            if (HttpContext.User.Identity.Name != null)
            {
                var email = HttpContext.User.Identity.Name;
                string[] slova = email.Split(' ');
                Debug.WriteLine(slova[0]);
                User t = await dbs.GetUserPoEmail(slova[0]);
                Debug.WriteLine(t.Id);
                List<Korzina> ListKorzina = await db.GetTovariFromKorzina(t.Id.ToString());

                List<Tovar> itog = new List<Tovar>();
                foreach (var items in g.TovariList)
                {
                    foreach (var j in ListKorzina)
                    {
                        if (items.Id == j.id_tovara)
                        {
                            items.HasTovarInCart = true;
                            break;
                        }
                        else
                            items.HasTovarInCart = false;
                    }
                    itog.Add(items);
                }
                g.TovariList = itog;
            }

            return View(g);
        }


        public async Task<IActionResult> TovariPodCategorii(string id, int page = 1)
        {
            PodCatG g = new PodCatG();
            g.podcategs = await db.GetPodCategoriesPoID(id);
            g.categMain = await db.GetIDCategoriiWithName(g.podcategs.NameCategori);

            g.TovariList = await db.GetTovariWithFilterAndCategori(null, g.podcategs.NameCategori, g.podcategs.NamePodCategori);
            g.KolTovarov = g.TovariList.Count().ToString();

            var count = g.TovariList.Count();
            int pageSize = 10;
            var item = g.TovariList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            g.PageViewModel = new PageViewModel(count, page, pageSize);
            g.TovariList = item;

            if (HttpContext.User.Identity.Name != null)
            {
                var email = HttpContext.User.Identity.Name;
                string[] slova = email.Split(' ');
                Debug.WriteLine(slova[0]);
                User t = await dbs.GetUserPoEmail(slova[0]);
                Debug.WriteLine(t.Id);
                List<Korzina> ListKorzina = await db.GetTovariFromKorzina(t.Id.ToString());

                List<Tovar> itog = new List<Tovar>();
                foreach (var items in g.TovariList)
                {
                    foreach (var j in ListKorzina)
                    {
                        if (items.Id == j.id_tovara)
                        {
                            items.HasTovarInCart = true;
                            break;
                        }
                        else
                            items.HasTovarInCart = false;
                    }
                    itog.Add(items);
                }
                g.TovariList = itog;
            }

            return View(g);
        }

        public async Task<IActionResult> Tovar(string id)
        {
            PodCatG g = new PodCatG();
            g.tovar = await db.GetTovarPoID(id);
            g.podcategs = await db.GetIDPodCategoriiWithName(g.tovar.NamePodCategori);
            g.categMain = await db.GetIDCategoriiWithName(g.tovar.NameCategori);

            if (HttpContext.User.Identity.Name != null)
            {
                var email = HttpContext.User.Identity.Name;
                string[] slova = email.Split(' ');
                Debug.WriteLine(slova[0]);
                User t = await dbs.GetUserPoEmail(slova[0]);
                Debug.WriteLine(t.Id);
                List<Korzina> ListKorzina = await db.GetTovariFromKorzina(t.Id.ToString());
                
                foreach(var item in ListKorzina)
                {
                    if(item.id_tovara == g.tovar.Id)
                    {
                        g.tovar.HasTovarInCart = true;
                        break;
                    }
                }
            }

            return View(g);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Korzina(/*string id, int page = 1*/)
        {
            TovariInCart g = new TovariInCart();

            if (HttpContext.User.Identity.Name != null)
            {
                var email = HttpContext.User.Identity.Name;
                string[] slova = email.Split(' ');
                Debug.WriteLine(slova[0]);
                User t = await dbs.GetUserPoEmail(slova[0]);
                Debug.WriteLine(t.Id);

                List<Korzina> ListKorzina = await db.GetTovariFromKorzina(t.Id.ToString());
                List<Tovar> toval = new List<Tovar>();

                foreach (var h in ListKorzina)
                {
                    toval.Add(await db.GetTovarPoID(h.id_tovara));
                }

                List<TovarForCart> itog = new List<TovarForCart>();

                foreach(var item in toval)
                {
                    TovarForCart k = new TovarForCart();
                    foreach(var items in ListKorzina)
                    {
                        if(item.Id == items.id_tovara)
                        {
                            k.Id = item.Id;
                            k.ImageId = item.ImageId;
                            k.Cena = item.Cena;
                            k.HasTovarInCart = true;
                            k.kolvo_tovara = items.kolvo_tovara;
                            k.ModelTovar = item.ModelTovar;
                            k.NameCategori = item.NameCategori;
                            k.NamePodCategori = item.NamePodCategori;
                            k.NameTovar = item.NameTovar;
                            k.StranaProizvoditel = item.StranaProizvoditel;
                            g.summazakaza = (Convert.ToDouble(g.summazakaza) + Convert.ToDouble(k.Cena) * k.kolvo_tovara).ToString();
                            itog.Add(k);
                        }
                    }
                }
                g.Korzina = itog;
            }
            return View(g);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Korzina(TovariInCart g)
        {
            Debug.WriteLine(g.zakaz.Address_Dom);
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                var email = HttpContext.User.Identity.Name;
                string[] slova = email.Split(' ');
                Debug.WriteLine(slova[0]);
                User t = await dbs.GetUserPoEmail(slova[0]);
                await db.CreateZakaz(t.Id,g);
                return RedirectToAction("Index","Home");
            }
            else
                ModelState.AddModelError("", "");

            return View("Korzina", g);//("RegistrateUser", model);
        }

        [Authorize]
        public async Task<IActionResult> MyZakazi()
        {
            var email = HttpContext.User.Identity.Name;
            string[] slova = email.Split(' ');
            Debug.WriteLine(slova[0]);
            User t = await dbs.GetUserPoEmail(slova[0]);
            ZakazUser z = new ZakazUser();
            z.zakazes = await db.GetZakaziUsera(t.Id);
            return View(z);
        }

        [Authorize]
        public async Task<IActionResult> ZakazUser(string id)
        {
            ZakazUser z = new ZakazUser();
            z.zakaz = new Zakaz();
            z.zakaz = await db.GetZakazPoID(id);
            Debug.WriteLine(id+"  :"+z.zakaz.Id + " " + z.zakaz.status);
            return View(z);
        }

        [HttpPost]
        public async Task<IActionResult> resultPoiskaAsync(string search)
        {
            PoiskTovarov g = new PoiskTovarov();
            if (search != null && search.Trim() != "")
            {
                search = search.Trim();
                g.search_string = search;
                g.TovariResult = await db.GetTovariToSearch(search);
            }
            else
            {
                g.TovariResult = null;
            }
            return View(g);
        }
    }
}

ShopMagazin/Views/Categorii/MyZakazi.cshtml
@model ShopMagazin.Models.ZakazUser
@{
    ViewData["Title"] = "Заказы";
}

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" defer></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" defer></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="~/lib/jQuery-Mask-Plugin-master/dist/jquery.mask.js"></script>
<link rel="stylesheet" type="text/css" href="~/css/style_table.css" />
<main class="content-main">
    <div class="con-man">
        <div class="main-div-left">
            <main class="main">
                <header style="margin: 0;" class="page-header">
                    <h1>Мои заказы</h1>
                </header>
                @if (Model.zakazes.Count() > 0)
                {
                    <table class="table custom-table" style=" min-width: 850px;">
                        <thead>
                            <tr>
                                <th scope="col">Номер заказа</th>
                                <th scope="col">Статус заказа</th>
                                <th scope="col">Итоговая цена</th>
                                <th scope="col">Действия</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.zakazes)
                            {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.status</td>
                                <td>@item.StoimostZakakaAll₽</td>
                                <td>
                                    <a asp-controller="Categorii" asp-action="ZakazUser" class="edus" asp-route-id="@item.Id" style="text-decoration: none; margin-right: 15px;">
                                        Просмотреть
                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <h1>Заказов нету :(</h1>
                }
            </main>
        </div>
        <div class="notmain-div-right">
            <div class="block-right">
                <aside class="aside aside_user">
                    <div class="aside__user-info">
                        <div class="user-line">
                            <div class="user-line__avatar">
                                <img src="https://vasko.ru/images/user_outline.svg" alt="avatar">
                            </div>
                            <div class="user-line__name">
                                <div>
                                    @{
                                        string g = User.Identity.Name;
                                        g = g.Substring(g.IndexOf(' ') + 1);
                                        <b>
                                            @g
                                        </b>
                                    }
                                </div>
                            </div>
                        </div>
                        <menu class="user-menu">
                            <li class="user-menu__item">
                                <a asp-action="Korzina" asp-controller="Categorii" class="user-menu__link user-menu__item_active">
                                    <svg class="icon user-menu__icon" width="27" height="23" viewBox="0 0 27 23" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M21.273 2.80943L8.14509 8.26933V11.7754L5.85494 10.8745V7.36846L18.9829 1.9086L14.5735 0.174169C13.983 -0.0580562 13.017 -0.0580562 12.4265 0.174169L1.5687 4.44516C0.703681 4.78541 -0.00220073 5.74897 5.15601e-06 6.58646L0.0267404 16.5988C0.0289904 17.4452 0.750623 18.4098 1.63033 18.7426L12.4597 22.838C13.0308 23.054 13.9654 23.054 14.5365 22.8381L25.3696 18.7425C26.2493 18.41 26.971 17.4454 26.9732 16.5991L27 6.58646C27.0022 5.74897 26.2964 4.78541 25.4313 4.44516L21.273 2.80943ZM24.547 10.8238L23.9115 11.0846L23.8987 15.0404C23.8981 15.2132 23.7255 15.419 23.5136 15.4999L22.5623 15.8632C22.3538 15.9429 22.1851 15.869 22.185 15.6984L22.1817 11.7946L21.5662 12.0472C21.2767 12.166 21.0956 11.9797 21.2393 11.7115L22.7105 8.96558C22.859 8.68839 23.2314 8.52849 23.3804 8.67883L24.8902 10.2014C25.0409 10.3534 24.8496 10.6997 24.547 10.8238ZM18.3351 17.1765C18.3367 17.3421 18.1785 17.5372 17.9821 17.6122L17.1 17.9491C16.9065 18.023 16.7482 17.9502 16.746 17.7867L16.6944 14.0467L16.1236 14.281C15.8551 14.3911 15.6838 14.2104 15.8145 13.9553L17.1517 11.345C17.2866 11.0816 17.6314 10.9336 17.7721 11.0794L19.1971 12.5561C19.3395 12.7035 19.1657 13.0323 18.8856 13.1473L18.2971 13.3888L18.3351 17.1765ZM25.5971 16.0906C25.5964 16.1775 25.5082 16.2805 25.4 16.3207L15.3237 20.0656C15.2297 20.1005 15.1524 20.0639 15.151 19.9838L15.1433 19.5481C15.1419 19.4678 15.217 19.3739 15.3112 19.3385L25.4054 15.5344C25.5137 15.4936 25.6012 15.531 25.6005 15.6181L25.5971 16.0906Z" fill="#C62306" />
                                    </svg> Корзина
                                </a>
                            </li>
                            <li class="user-menu__item">
                                <a href="/personal/profiles/" class="user-menu__link">
                                    <svg class="icon user-menu__icon" width="21" height="12" viewBox="0 0 21 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M7.78332 11.2066H0.0566406C0.0566406 9.41804 1.08937 7.89337 2.54156 7.28843C2.22986 6.92842 2.0035 6.38102 1.88996 5.55498C1.74025 5.5895 1.50811 5.3947 1.4394 5.09799C1.36925 4.79634 1.32369 4.30893 1.47484 4.26208C1.51968 4.24811 1.56668 4.25797 1.61225 4.2851V3.44673C1.61225 2.12671 1.33888 1.35081 3.23728 1.12971L3.22065 1.12478C3.22065 1.12478 4.71695 0.961217 5.11109 0.558472C5.11109 0.558472 5.12194 0.89875 5.28105 1.27191C6.15684 1.65328 6.26677 2.53521 6.24146 3.44755V4.28674C6.28774 4.25962 6.33475 4.24976 6.37959 4.26373C6.53074 4.31058 6.45046 4.81606 6.38104 5.11936C6.31306 5.41278 6.11707 5.58786 5.96881 5.55662C5.85816 6.34321 5.61517 6.90787 5.27815 7.2835C6.74119 7.88104 7.78332 9.40818 7.78332 11.2066ZM20.6245 1.75356C20.6245 1.29962 20.2565 0.931628 19.8026 0.931628H10.7192C10.2652 0.931628 9.89724 1.29962 9.89724 1.75356V1.75356C9.89724 2.2075 10.2652 2.57549 10.7192 2.57549H19.8026C20.2565 2.57549 20.6245 2.2075 20.6245 1.75356V1.75356ZM20.6245 6.00046C20.6245 5.54652 20.2565 5.17853 19.8026 5.17853H10.7192C10.2652 5.17853 9.89724 5.54652 9.89724 6.00046V6.00046C9.89724 6.4544 10.2652 6.82239 10.7192 6.82239H19.8026C20.2565 6.82239 20.6245 6.4544 20.6245 6.00046V6.00046ZM20.6245 10.2482C20.6245 9.79425 20.2565 9.42626 19.8026 9.42626H10.7192C10.2652 9.42626 9.89724 9.79425 9.89724 10.2482V10.2482C9.89724 10.7021 10.2652 11.0701 10.7192 11.0701H19.8026C20.2565 11.0701 20.6245 10.7021 20.6245 10.2482V10.2482Z" fill="#C62306" />
                                    </svg> Профиль покупателя
                                </a>
                            </li>
                            <li class="user-menu__item">
                                <a asp-controller="Home" asp-action="Logout" class="user-menu__link">
                                    <svg class="icon user-menu__icon" width="27" height="19" viewBox="0 0 27 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M8.21829 14.3131C8.32256 14.1184 8.31111 13.8822 8.18865 13.6986L6.78293 11.5899H15.2889C16.457 11.5899 17.4073 10.6397 17.4073 9.47157C17.4073 8.30348 16.457 7.3532 15.2889 7.3532H6.78293L8.18865 5.24457C8.3112 5.06093 8.32256 4.82475 8.21829 4.63002C8.11411 4.43539 7.91129 4.31384 7.69047 4.31384H3.63811C3.43802 4.31384 3.25102 4.41384 3.14002 4.58048L0.100568 9.13947C-0.0335227 9.34057 -0.0335227 9.60247 0.100568 9.80366L3.13993 14.3627C3.25093 14.5292 3.43793 14.6293 3.63802 14.6293H7.69047C7.91138 14.6293 8.1142 14.5077 8.21829 14.3131Z" fill="#C62306" />
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M7 0.5625C5.34315 0.5625 4 1.90565 4 3.5625L17 3.5625C18.6569 3.5625 20 4.90565 20 6.5625V12.5625C20 14.2194 18.6569 15.5625 17 15.5625H4C4 17.2194 5.34315 18.5625 7 18.5625H24C25.6569 18.5625 27 17.2194 27 15.5625V3.5625C27 1.90565 25.6569 0.5625 24 0.5625H7Z" fill="#C62306" />
                                    </svg>Выйти из аккаунта
                                </a>
                            </li>
                        </menu>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</main>
<link rel="stylesheet" href="~/css/stylekorzina.css">