ShopMagazin/Controllers/TovariController.cs
using JWT.Algorithms;
using JWT.Builder;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Driver;
using ShopMagazin.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using PagedList.Mvc;
using PagedList;

namespace ShopMagazin.Controllers
{
    public class TovariController : Controller
    {
        private readonly TovariService db;
        public TovariController(TovariService context)
        {
            db = context;
        }

        /*Создание категорий*/

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("CreateCat")]
        public async Task<IActionResult> ConfirmCreateCat()
        {
            return PartialView();
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> CreateCat(Categorii p, IFormFile uploadedFile)
        {
            Debug.WriteLine(ModelState.IsValid.ToString());
            if (ModelState.IsValid)
            {
                await db.CreateCategori(p, uploadedFile.OpenReadStream(), uploadedFile.FileName);
                return RedirectToAction("IndexCategorii");
            }
            return View(p);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> IndexCategorii(string ZhachPoiska, int page = 1)
        {
            PodCatG g = new PodCatG();
            g.PodU = await db.GetCategories();
            g.ZhachPoiska = ZhachPoiska;
            if(ZhachPoiska != null)
            {
                g.PodU = await db.GetCategsWithFilter(ZhachPoiska);
            }

            int pageSize = 5;
            var count = g.PodU.Count();
            var item = g.PodU.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            g.PageViewModel = new PageViewModel(count, page, pageSize);
            g.PodU = item;

            return View(g);
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> CheckCategoris(Categorii p)
        {
            Debug.WriteLine(OldEmail.OldE + "  " + p.NameCategori);
            bool exists = db.CheckCategoris(p.NameCategori);
            if (exists && OldEmail.OldE != p.NameCategori)
                return Json(false);
            return Json(true);
        }

        public async Task<ActionResult> GetImage(string id)
        {
            var image = await db.GetImage(id);
            if (image == null)
            {
                return NotFound();
            }
            return File(image, "image/png");
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("EditCat")]
        public async Task<IActionResult> ConfirmEdit(string id)
        {
            Categorii p = await db.GetCategoriesPoID(id);
            Debug.WriteLine("Стар: " + p.NameCategori);
            OldEmail.OldE = p.NameCategori;
            if (p != null)
                return PartialView(p);
            return View();
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> EditCat(Categorii p, IFormFile uploadedFile)
        {
            if (uploadedFile == null)
                await db.UpdateCategori(p, null, "");
            else
                await db.UpdateCategori(p, uploadedFile.OpenReadStream(), uploadedFile.FileName);
            return RedirectToAction("IndexCategorii");
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("DeleteCat")]
        public async Task<IActionResult> ConfirmDeleteCat(string id)
        {
            Categorii p = await db.GetCategoriesPoID(id);
            return PartialView(p);
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> DeleteCat(string id)
        {
            await db.RemoveCategori(id);
            return RedirectToAction("IndexCategorii");
        }


        //ПОДКАТЕГОРИИ
        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> IndexPodCategorii(string ZhachPoiska, string ZnachPoiskaCateg, int page = 1)
        {
            Debug.WriteLine("sfdfafafffas^: " + ZhachPoiska);
            Debug.WriteLine("1212sfdfafafffas^: " + ZnachPoiskaCateg);
            PodCatG g = new PodCatG();
            g.PodCategsList = await db.GetPodCategories();
            g.PodU = await db.GetCategories();

            int pageSize = 5;
            var count = g.PodCategsList.Count();
            var item = g.PodCategsList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            g.PageViewModel = new PageViewModel(count, page, pageSize);
            g.PodCategsList = item;

            PodCatG t = new PodCatG();
            t.ZhachPoiska = ZhachPoiska;
            t.ZnachPoiskaCateg = ZnachPoiskaCateg;

            if (t != null)
            {
                if (t.ZnachPoiskaCateg == "Все")
                    t.ZnachPoiskaCateg = null;

                g.PodCategsList = await db.GetPodCategsWithFilter(t.ZhachPoiska, t.ZnachPoiskaCateg);

                count = g.PodCategsList.Count();
                item = g.PodCategsList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                g.PageViewModel = new PageViewModel(count, page, pageSize);
                g.PodCategsList = item;

                if (t.ZhachPoiska != null)
                    g.ZhachPoiska = t.ZhachPoiska;
                if (t.ZnachPoiskaCateg != null)
                    g.ZnachPoiskaCateg = t.ZnachPoiskaCateg;
            }

            if (t.ZhachPoiska != null)
            {
                if (t.ZhachPoiska.Trim() != "")
                {
                    if (t.ZnachPoiskaCateg == "Все")
                    {

                        g.PodCategsList = await db.GetPodCategsWithFilter(t.ZhachPoiska, null);

                        count = g.PodCategsList.Count();
                        item = g.PodCategsList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                        g.PageViewModel = new PageViewModel(count, page, pageSize);
                        g.PodCategsList = item;

                        return View(g);
                    }
                    else
                    {
                        return View(g);
                    }
                }
            }
            else if (t.ZnachPoiskaCateg != "Все")
            {
                g.PodCategsList = await db.GetPodCategsWithFilter(t.ZhachPoiska, t.ZnachPoiskaCateg);

                count = g.PodCategsList.Count();
                item = g.PodCategsList.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                g.PageViewModel = new PageViewModel(count, page, pageSize);
                g.PodCategsList = item;

                return View(g);
            }
            else
                return View(g);
            return View(g);
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> CheckPodCategoris(PodCatG p)
        {
            //Debug.WriteLine(OldEmail.OldE + "  " + p.NameCategori);
            bool exists = db.CheckPodCategoris(p.podcategs.NamePodCategori);
            if (exists && OldEmail.OldE != p.podcategs.NamePodCategori)
                return Json(false);
            return Json(true);
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("CreatePodCat")]
        public async Task<IActionResult> ConfirmCreatePodCat()
        {
            PodCatG t = new PodCatG();
            t.PodU = await db.GetCategories();
            return PartialView(t);
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> CreatePodCat(PodCatG p, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                await db.CreatePodCat(p, uploadedFile.OpenReadStream(), uploadedFile.FileName);
                return RedirectToAction("IndexPodCategorii");
            }
            return View(p);
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("DeletePodCat")]
        public async Task<IActionResult> ConfirmDeletePodCat(string id)
        {
            PodCatG g = new PodCatG();
            g.podcategs = await db.GetPodCategoriesPoID(id);
            return PartialView(g);
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> DeletePodCat(string id)
        {
            await db.RemovePodCategori(id);
            return RedirectToAction("IndexPodCategorii");
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("EditPodCat")]
        public async Task<IActionResult> ConfirmPodEdit(string id)
        {
            PodCatG g = new PodCatG();
            g.podcategs = await db.GetPodCategoriesPoID(id);
            g.PodU = await db.GetCategories();
            OldEmail.OldE = g.podcategs.NamePodCategori;
            if (g != null)
                return PartialView(g);
            return View();
        }

        [Authorize(Roles = "Администратор")]
        [HttpPost]
        public async Task<IActionResult> EditPodCat(PodCatG p, IFormFile uploadedFile)
        {
            if (uploadedFile == null)
                await db.UpdatePodCategori(p, null, "");
            else
                await db.UpdatePodCategori(p, uploadedFile.OpenReadStream(), uploadedFile.FileName);
            return RedirectToAction("IndexPodCategorii");
        }
    }
}

ShopMagazin/Views/Tovari/CreateCat.cshtml
@model ShopMagazin.Models.Categorii

<link rel="stylesheet" type="text/css" href="~/css/style_list.css" />
<link rel="stylesheet" type="text/css" href="~/css/styleInputFile.css" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class="modal-content">
    <div class="modal-windows">
        <div class="obratnii-zvonok">
            <div class="form-edit fformms" style="padding: 30px; background-color: #fff; border-radius: 5px; box-shadow: 1px 1px 10px 0 rgb(0 0 0 / 12%); color: #696969; ">
                <div class="zvonok-title">Добавление категории</div>
                <form asp-action="CreateCat" asp-controller="Tovari" method="post" class="callback-from" enctype="multipart/form-data">
                    <div>
                        <div class="form-zap">
                            <label asp-for="NameCategori" class="required"></label>
                            <input type="text" asp-for="NameCategori" class="inputs imz-in" />
                            <span asp-validation-for="NameCategori" style="color: red;"></span>
                        </div>

                        <label asp-for="ImageId" class="required"></label>
                        <div class="form-zap">
                            <div class="profile-picture-upload">
                                <img src="" alt="Profile picture preview" class="imagePreview">
                                <a class="action-button mode-upload" style="margin-top: 15px; color: White;">Загрузить</a>
                                <input accept="image/png, image/jpg, image/jpeg" type="file" id="olo" class="hidden" name="uploadedFile" />
                            </div>
                        </div>
                        <span asp-validation-for="ImageId" style="color: red;"></span>

                        <script type="text/javascript">
                            document.getElementById('olo').addEventListener('change', function () {
                                if (this.value) {
                                    document.getElementById('checker').value = 'true';
                                    console.log(document.getElementById('checker').value);
                                }
                            });

                            picturePreview = document.querySelector(".imagePreview");
                            actionButton = document.querySelector(".action-button");
                            fileInput = document.querySelector("input[name='uploadedFile']");
                            fileReader = new FileReader();

                            DEFAULT_IMAGE_SRC = "https://cs6.pikabu.ru/avatars/852/v852649-75385198.jpg"/*"https://www.drupal.org/files/profile_default.png"*/;

                            actionButton.addEventListener("click", () => {
                                if (picturePreview.src !== DEFAULT_IMAGE_SRC) {
                                    resetImage();
                                } else {
                                    fileInput.click();
                                }
                            });

                            fileInput.addEventListener("change", () => {
                                refreshImagePreview();
                            });

                            function resetImage() {
                                setActionButtonMode("upload");
                                picturePreview.src = DEFAULT_IMAGE_SRC;
                                document.getElementById('checker').value = '';
                                fileInput.value = "";
                            }

                            function setActionButtonMode(mode) {
                                let modes = {
                                    "upload": function () {
                                        actionButton.innerText = "Загрузить";
                                        actionButton.classList.remove("mode-remove");
                                        actionButton.classList.add("mode-upload");
                                    },
                                    "remove": function () {
                                        actionButton.innerText = "Удалить";
                                        actionButton.classList.remove("mode-upload");
                                        actionButton.classList.add("mode-remove");
                                    }
                                }
                                return (modes[mode]) ? modes[mode]() : console.error("unknown mode");
                            }

                            function refreshImagePreview() {
                                if (picturePreview.src !== DEFAULT_IMAGE_SRC) {
                                    picturePreview.src = DEFAULT_IMAGE_SRC;
                                } else {
                                    if (fileInput.files && fileInput.files.length > 0) {
                                        var fileName = fileInput.value,
                                            idxDot = fileName.lastIndexOf(".") + 1,
                                            extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
                                        console.log("hsjfd  " + fileName);
                                        if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {
                                            fileReader.readAsDataURL(fileInput.files[0]);
                                            fileReader.onload = (e) => {
                                                picturePreview.src = e.target.result;
                                                setActionButtonMode("remove");
                                            }
                                        }
                                        else {
                                            alert("Только jpg/jpeg и png файлы можно использовать!");
                                            fileInput.value = "";
                                            document.getElementById('checker').value = '';
                                        }
                                    }
                                }
                            }

                            refreshImagePreview();
                        </script>
                        <input type="text" asp-for="ImageId" id="checker" value="" class="inputs imz-in" style="width: 0; height: 0; opacity: 0;" />
                        <div class="form-zap">
                            <div class="btn-center">
                                <input class="sbm-zvonok" type="submit" value="Создать" />
                            </div>
                        </div>
                    </div>
                </form>
                <div class="btn-center">
                    <button class="sbm-zvonok otm" style="background-color: #c4c4c4; margin-top: 15px; color: White;" onclick='$(".modal-content").remove();'>Отмена</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" defer></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" defer></script>

ShopMagazin/Views/Tovari/CreatePodCat.cshtml
@model ShopMagazin.Models.PodCatG
@*@model IEnumerable<ShopMagazin.Models.Categorii>*@

<link rel="stylesheet" type="text/css" href="~/css/style_list.css" />
<script type="text/javascript" src="~/js/script_list.js" defer></script>
<link rel="stylesheet" type="text/css" href="~/css/styleInputFile.css" />
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class="modal-content">
    <div class="modal-windows">
        <div class="obratnii-zvonok">
            <div class="form-edit fformms" style="padding: 30px; background-color: #fff; border-radius: 5px; box-shadow: 1px 1px 10px 0 rgb(0 0 0 / 12%); color: #696969; ">
                <div class="zvonok-title">Добавление категории</div>
                <form asp-action="CreatePodCat" asp-controller="Tovari" method="post" class="callback-from" enctype="multipart/form-data">
                    <div>
                        <div class="form-group">
                            <label asp-for="@Model.podcategs.NameCategori" class="required"></label>
                            <input asp-for="@Model.podcategs.NameCategori" type="text" id="rod" style="opacity: 0; width: 0px; height: 0px;" />
                            <div class="dropdown1" style="margin-bottom: 15px;">
                                <div class="select">
                                    <span id="rod1">Выберите основную категорию</span>
                                    <i class="fa fa-chevron-left"></i>
                                </div>
                                <ul class="dropdown-menu1">
                                    @foreach (var item in Model.PodU)
                                    {
                                        <li>@item.NameCategori</li>
                                    }
                                </ul>
                            </div>
                            <span asp-validation-for="@Model.podcategs.NameCategori" style="color: red;"></span>
                        </div>

                        <div class="form-zap">
                            <label asp-for="@Model.podcategs.NamePodCategori" class="required"></label>
                            <input type="text" asp-for="@Model.podcategs.NamePodCategori" class="inputs imz-in" />
                            <span asp-validation-for="@Model.podcategs.NamePodCategori" style="color: red;"></span>
                        </div>

                        <label asp-for="@Model.podcategs.ImageId" class="required"></label>
                        <div class="form-zap">
                            <div class="profile-picture-upload">
                                <img src="" alt="Profile picture preview" class="imagePreview">
                                <a class="action-button mode-upload" style="margin-top: 15px; color: White;">Загрузить</a>
                                <input accept="image/png, image/jpg, image/jpeg" type="file" id="olo" class="hidden" name="uploadedFile" />
                            </div>
                        </div>
                        <span asp-validation-for="@Model.podcategs.ImageId" style="color: red;"></span>
                        <script type="text/javascript">
                            document.getElementById('olo').addEventListener('change', function () {
                                if (this.value) {
                                    document.getElementById('checker').value = 'true';
                                    console.log(document.getElementById('checker').value);
                                }
                            });

                            picturePreview = document.querySelector(".imagePreview");
                            actionButton = document.querySelector(".action-button");
                            fileInput = document.querySelector("input[name='uploadedFile']");
                            fileReader = new FileReader();

                            DEFAULT_IMAGE_SRC = "https://cs6.pikabu.ru/avatars/852/v852649-75385198.jpg"/*"https://www.drupal.org/files/profile_default.png"*/;

                            actionButton.addEventListener("click", () => {
                                if (picturePreview.src !== DEFAULT_IMAGE_SRC) {
                                    resetImage();
                                } else {
                                    fileInput.click();
                                }
                            });

                            fileInput.addEventListener("change", () => {
                                refreshImagePreview();
                            });

                            function resetImage() {
                                setActionButtonMode("upload");
                                picturePreview.src = DEFAULT_IMAGE_SRC;
                                document.getElementById('checker').value = '';
                                fileInput.value = "";
                            }

                            function setActionButtonMode(mode) {
                                let modes = {
                                    "upload": function () {
                                        actionButton.innerText = "Загрузить";
                                        actionButton.classList.remove("mode-remove");
                                        actionButton.classList.add("mode-upload");
                                    },
                                    "remove": function () {
                                        actionButton.innerText = "Удалить";
                                        actionButton.classList.remove("mode-upload");
                                        actionButton.classList.add("mode-remove");
                                    }
                                }
                                return (modes[mode]) ? modes[mode]() : console.error("unknown mode");
                            }

                            function refreshImagePreview() {
                                if (picturePreview.src !== DEFAULT_IMAGE_SRC) {
                                    picturePreview.src = DEFAULT_IMAGE_SRC;
                                } else {
                                    if (fileInput.files && fileInput.files.length > 0) {
                                        var fileName = fileInput.value,
                                            idxDot = fileName.lastIndexOf(".") + 1,
                                            extFile = fileName.substr(idxDot, fileName.length).toLowerCase();
                                        console.log("hsjfd  " + fileName);
                                        if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {
                                            fileReader.readAsDataURL(fileInput.files[0]);
                                            fileReader.onload = (e) => {
                                                picturePreview.src = e.target.result;
                                                setActionButtonMode("remove");
                                            }
                                        }
                                        else {
                                            alert("Только jpg/jpeg и png файлы можно использовать!");
                                            fileInput.value = "";
                                            document.getElementById('checker').value = '';
                                        }
                                    }
                                }
                            }

                            refreshImagePreview();
                        </script>
                        <input type="text" asp-for="@Model.podcategs.ImageId" id="checker" value="" class="inputs imz-in" style="width: 0; height: 0; opacity: 0;" />
                        <div class="form-zap">
                            <div class="btn-center">
                                <input class="sbm-zvonok" type="submit" value="Создать" />
                            </div>
                        </div>
                    </div>
                </form>
                <div class="btn-center">
                    <button class="sbm-zvonok otm" style="background-color: #c4c4c4; margin-top: 15px; color: White;" onclick='$(".modal-content").remove();'>Отмена</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js" defer></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" defer></script>

ShopMagazin/Views/Tovari/DeleteCat.cshtml
@model ShopMagazin.Models.Categorii

    <div class="modal-content">
        <div class="modal-windows">
            <div class="obratnii-zvonok">
                <div class="form-delete fformms" style="padding: 30px; background-color: #fff; border-radius: 5px; box-shadow: 1px 1px 10px 0 rgb(0 0 0 / 12%); color: #696969; ">
                    <div class="zvonok-title">Удаление категории</div>
                    <form asp-controller="Tovari" asp-action="DeleteCat" method="post" class="callback-from">
                        <div class="info-zvonok">Вы правда желаете удалить данную категорию и её подкатегории?</div>
                        <div class="form-zap">
                            <label class="nonrequired">Наименование категории:</label>
                            <label class="nonrequired" style="color: black;">@Html.DisplayFor(model => model.NameCategori)</label>
                        </div>

                        <label asp-for="ImageId" class="nonrequired"></label>
                        <div class="form-zap">
                            <div class="profile-picture-upload">
                                <img src="@Url.Action("GetImage", new { id=Model.ImageId})" style=" width: 64px; height: 64px;" alt="Profile picture preview" class="imagePreview">
                            </div>
                        </div>
                        <div class="form-zap">
                            <div class="btn-center">
                                <input class="sbm-zvonok" type="submit" value="Удалить" />
                            </div>
                        </div>
                    </form>
                    <div class="btn-center">
                        <button class="sbm-zvonok otm" style="background-color: #c4c4c4; margin-top: 15px; color: White;" onclick='$(".modal-content").remove();'>Отмена</button>
                    </div>
                </div>
             </div>
        </div>
    </div>

ShopMagazin/Views/Tovari/DeletePodCat.cshtml
@model ShopMagazin.Models.PodCatG

    <div class="modal-content">
        <div class="modal-windows">
            <div class="obratnii-zvonok">
                <div class="form-delete fformms" style="padding: 30px; background-color: #fff; border-radius: 5px; box-shadow: 1px 1px 10px 0 rgb(0 0 0 / 12%); color: #696969; ">
                    <div class="zvonok-title">Удаление категории</div>
                    <form asp-controller="Tovari" asp-action="DeletePodCat" method="post" class="callback-from">
                        <div class="info-zvonok">Вы правда желаете удалить данную подкатегорию</div>
                        <div class="form-zap">
                            <label class="nonrequired">Наименование подкатегории:</label>
                            <label class="nonrequired" style="color: black;">@Html.DisplayFor(model => model.podcategs.NamePodCategori)</label>
                        </div>

                        <div class="form-zap">
                            <label class="nonrequired">Категория:</label>
                            <label class="nonrequired" style="color: black;">@Html.DisplayFor(model => model.podcategs.NameCategori)</label>
                        </div>

                        <label asp-for="@Model.podcategs.ImageId" class="nonrequired"></label>
                        <div class="form-zap">
                            <div class="profile-picture-upload">
                                <img src="@Url.Action("GetImage", new { id=Model.podcategs.ImageId})" style=" width: 64px; height: 64px;" alt="Profile picture preview" class="imagePreview">
                            </div>
                        </div>
                        <div class="form-zap">
                            <div class="btn-center">
                                <input class="sbm-zvonok" type="submit" value="Удалить" />
                            </div>
                        </div>
                    </form>
                    <div class="btn-center">
                        <button class="sbm-zvonok otm" style="background-color: #c4c4c4; margin-top: 15px; color: White;" onclick='$(".modal-content").remove();'>Отмена</button>
                    </div>
                </div>
             </div>
        </div>
    </div>